package com.cardgame.cards;

public enum CardType {
	EMPTY,	
	GIVE_OPPONENT_SCORE,
	TAKE_MINUS_POINTS,
	INCREASE_HAND_LIMIT_FOR_OPPONENT,
	REMOVE_CURSE_FROM_OPPONENT,
	DECREASE_HAND_LIMIT,
	TAKE_MINUS_POINTS_AND_DISCARD_HAND,
	PLAY_TOPMOST_CARD,
	SWITCH_SCORE_WITH_OPPONENT,
	INCREASE_PLAYED_CARDS_AND_SCORE,
}
